### PR TITLE
Fix Mouse back button not doing anything

### LINKED ISSUE #1565: Mouse Back Button does not do anything
**Platform:** Arch Linux 6.7.6-arch1-2

**Nuclear version:** 0.6.30

**Description of the issue:**
Using the back button on the mouse does not do anything. I would have expected it to do the same thing as the gui back button. Same for the forwards button.

Steps:
1. Have a mouse with a forward and back button
2. Open Nuclear and start navigating around the UI
3. Click mouse back button (doesn't do anything)
4. Click the gui back button (does go back to the last place you were)
5. Do the same for the forwards button

### PR DESCRIPTION
**Pull request by hollow-owl**
Fixes #1565 

react-router is controlling the history so electrons [`win.webContents.goBack()`](https://www.electronjs.org/docs/latest/api/browser-window#event-app-command-windows-linux) does not do anything. 

The code handling `navigate-back` and `navigate-forward` can go on pretty much any component that is always mounted. I didn't know whether to put it in App or NavButtons. I ended up with App instead of NavButtons just in case there is a UI where NavButtons are not enabled.

### CODE REVIEW

File: packages/app/app/App.js [hunk 1]
```diff
@@ -68,6 +72,26 @@ class App extends React.PureComponent {
     this.updateConnectivityStatus(navigator.onLine);
     window.addEventListener('online', () => this.updateConnectivityStatus(true));
     window.addEventListener('offline', () => this.updateConnectivityStatus(false));
+
+    ipcRenderer.on('navigate-back', this.handleBack);
```
Comment (nukeop) [inline packages/app/app/App.js:76]: Could you define these events in `@nuclear/core` in the IpcEvents enum?

Comment (nukeop) [reply packages/app/app/App.js:76]: And a better place for this is the IpcContainer

**Review by nukeop — CHANGES_REQUESTED** [review]

File: packages/app/app/App.js (hunk 1 above)
Comment (hollow-owl) [reply packages/app/app/App.js]: Moved it to IpcContainer and defined the events in IpcEvents

**Comment by nukeop** [comment]
Thanks, I merged your PR.
